### ISSUE TITLE
New PAI version (2.3.0) doesn't start

### ISSUE THREAD

**Issue by kovaccs** [ParadoxAlarmInterface/pai#205]
## Alarm system
Panel model (ex: EVO192), access mode (Serial, IP150).

## Environment
- RPI...  HassOS 5.11
## Describe the bug
Tthere are a lot of configuration parameters without any explanation.
The parameters of the previous version cannot be used or are incorrect.
Which parameter should be replaced and which should be omitted due to the new version?

## To Reproduce
Failed to save addon configuration, not a valid value for dictionary value @ data['options']. Got {'LOGGING_LEVEL_CONSOLE': 20, 'LOGGING_LEVEL_FILE': 40, 'CONNECTION_TYPE': 'IP', 'SERIAL_PORT': '/dev/ttyUSB0', 'SERIAL_BAUD': 9600, 'IP_CONNECTION_HOST': '172.30.1.xxx', 'IP_CONNECTION_PORT': 10000, 'IP_CONNECTION_PASSWORD': '*********', 'KEEP_ALIVE_INTERVAL': 10, 'LIMITS': {}, 'SYNC_TIME': True, 'SYNC_TIME_MIN_DRIFT': 120, 'PASSWORD': '****', 'MQTT_ENABLE': True, 'MQTT_HOST': 'core-mosquitto', 'MQTT_PORT': 1883, 'MQTT_KEEPALIVE': 60, 'MQTT_USERNAME': '*******', 'MQTT_PASSWORD': '***************', 'MQ...

Kovaccsaba

**Comment by rob196** [comment]
Had the same issue after updating
It seems like it doesn't like some config anymore

What I noticed (as config was updated/changed after the update):

1. PASSWORD - needed to wrap in single quotes now
2. MQTT_BIND_PORT - mine was set to 0, I removed this line
3. I removed all the below as well

LOGGING_FILE: null
LOGGING_DUMP_PACKETS: false
LOGGING_DUMP_MESSAGES: false
LOGGING_DUMP_STATUS: false
LOGGING_DUMP_EVENTS: true
IP_CONNECTION_SITEID: null
IP_CONNECTION_EMAIL: null
IP_CONNECTION_PANEL_SERIAL: null
IP_CONNECTION_BARE: false

Once that was done I was able to save the config

May be for a workaround, backup your current config, uninstall the add-on, then re-install
Then populate the provided fields (basically what I did now and it seems to be working)

**Comment by brendanpward** [comment]
Copy and save your old config to a text file on your local computer.  Press the three dots above the configuration and 'Reset to defaults'.  This will overwrite your old configuration.  It should start and run with this default configuration.  Then go line by line adding your old configuration back using the new format.  Be sure to save after each line to find where the formatting might be different.

**Comment by kovaccs** [comment]
Than you @brendanpward!
I corrected it based on your helpful information.

Kovaccsaba

**Comment by kovaccs** [comment]
Same as @rob196 !

**Comment by proasnet** [comment]
I thing that now are problems with new configuration scheme. I had function older version 2.5.5 last one week before update HA and PAI. Today I can not run. Now documentation for config is not actual and I dont know how config it to run as an older config. Still not wotking. PAI can not connect to panel.

**Comment by clau-bucur** [comment]
@proasnet see @brendanpward's instructions 3 comments above yours.

**Comment by yozik04** [comment]
Was it resolved?

**Comment by kovaccs** [comment]
I've done!

**Comment by yozik04** [comment]
Great! Closing.
